import '@ant-design/v5-patch-for-react-19';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";
import { initDb } from '@/lib/dbInit';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

await initDb();

// export default function RootLayout({ children }) {
//     return (
//         <html lang="en">
//             <body>
//
//                 <AuthProvider>{children}</AuthProvider>
//             </body>
//         </html>
//     );
// }
export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body suppressHydrationWarning>
        <AuthProvider>{children}</AuthProvider>
        </body>
        </html>
    );
}
